// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/spellingbee/v1/game.proto

package gamepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_game_proto_rawDescGZIP(), []int{0}
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server send letters to the client
	Letters []string `protobuf:"bytes,1,rep,name=letters,proto3" json:"letters,omitempty"`
	// client must always use the center letter in a word
	Center        string `protobuf:"bytes,2,opt,name=center,proto3" json:"center,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *StartResponse) GetLetters() []string {
	if x != nil {
		return x.Letters
	}
	return nil
}

func (x *StartResponse) GetCenter() string {
	if x != nil {
		return x.Center
	}
	return ""
}

type WordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// word that user typed in client
	Word          string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordRequest) Reset() {
	*x = WordRequest{}
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordRequest) ProtoMessage() {}

func (x *WordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordRequest.ProtoReflect.Descriptor instead.
func (*WordRequest) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *WordRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type WordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// validation for word
	Valid bool `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	// message for user about validation (valid or not)
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// points for word
	Score int32 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	// total points
	Total         int32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordResponse) Reset() {
	*x = WordResponse{}
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordResponse) ProtoMessage() {}

func (x *WordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_spellingbee_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordResponse.ProtoReflect.Descriptor instead.
func (*WordResponse) Descriptor() ([]byte, []int) {
	return file_api_spellingbee_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *WordResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *WordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WordResponse) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *WordResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_spellingbee_v1_game_proto protoreflect.FileDescriptor

const file_api_spellingbee_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/spellingbee/v1/game.proto\x12\x0espellingbee.v1\"\x0e\n" +
	"\fStartRequest\"A\n" +
	"\rStartResponse\x12\x18\n" +
	"\aletters\x18\x01 \x03(\tR\aletters\x12\x16\n" +
	"\x06center\x18\x02 \x01(\tR\x06center\"!\n" +
	"\vWordRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"j\n" +
	"\fWordResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total2\xa0\x01\n" +
	"\vSpellingBee\x12H\n" +
	"\tStartGame\x12\x1c.spellingbee.v1.StartRequest\x1a\x1d.spellingbee.v1.StartResponse\x12G\n" +
	"\n" +
	"SubmitWord\x12\x1b.spellingbee.v1.WordRequest\x1a\x1c.spellingbee.v1.WordResponseB'Z%spellingbee/api/spellingbee/v1;gamepbb\x06proto3"

var (
	file_api_spellingbee_v1_game_proto_rawDescOnce sync.Once
	file_api_spellingbee_v1_game_proto_rawDescData []byte
)

func file_api_spellingbee_v1_game_proto_rawDescGZIP() []byte {
	file_api_spellingbee_v1_game_proto_rawDescOnce.Do(func() {
		file_api_spellingbee_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_spellingbee_v1_game_proto_rawDesc), len(file_api_spellingbee_v1_game_proto_rawDesc)))
	})
	return file_api_spellingbee_v1_game_proto_rawDescData
}

var file_api_spellingbee_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_spellingbee_v1_game_proto_goTypes = []any{
	(*StartRequest)(nil),  // 0: spellingbee.v1.StartRequest
	(*StartResponse)(nil), // 1: spellingbee.v1.StartResponse
	(*WordRequest)(nil),   // 2: spellingbee.v1.WordRequest
	(*WordResponse)(nil),  // 3: spellingbee.v1.WordResponse
}
var file_api_spellingbee_v1_game_proto_depIdxs = []int32{
	0, // 0: spellingbee.v1.SpellingBee.StartGame:input_type -> spellingbee.v1.StartRequest
	2, // 1: spellingbee.v1.SpellingBee.SubmitWord:input_type -> spellingbee.v1.WordRequest
	1, // 2: spellingbee.v1.SpellingBee.StartGame:output_type -> spellingbee.v1.StartResponse
	3, // 3: spellingbee.v1.SpellingBee.SubmitWord:output_type -> spellingbee.v1.WordResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_spellingbee_v1_game_proto_init() }
func file_api_spellingbee_v1_game_proto_init() {
	if File_api_spellingbee_v1_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_spellingbee_v1_game_proto_rawDesc), len(file_api_spellingbee_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_spellingbee_v1_game_proto_goTypes,
		DependencyIndexes: file_api_spellingbee_v1_game_proto_depIdxs,
		MessageInfos:      file_api_spellingbee_v1_game_proto_msgTypes,
	}.Build()
	File_api_spellingbee_v1_game_proto = out.File
	file_api_spellingbee_v1_game_proto_goTypes = nil
	file_api_spellingbee_v1_game_proto_depIdxs = nil
}
