// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/spellingbee/v1/game.proto

package gamepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpellingBee_StartGame_FullMethodName  = "/spellingbee.v1.SpellingBee/StartGame"
	SpellingBee_SubmitWord_FullMethodName = "/spellingbee.v1.SpellingBee/SubmitWord"
)

// SpellingBeeClient is the client API for SpellingBee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// this is our service. client can call these 2rpc methods on the server
type SpellingBeeClient interface {
	StartGame(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	SubmitWord(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*WordResponse, error)
}

type spellingBeeClient struct {
	cc grpc.ClientConnInterface
}

func NewSpellingBeeClient(cc grpc.ClientConnInterface) SpellingBeeClient {
	return &spellingBeeClient{cc}
}

func (c *spellingBeeClient) StartGame(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, SpellingBee_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spellingBeeClient) SubmitWord(ctx context.Context, in *WordRequest, opts ...grpc.CallOption) (*WordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WordResponse)
	err := c.cc.Invoke(ctx, SpellingBee_SubmitWord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpellingBeeServer is the server API for SpellingBee service.
// All implementations must embed UnimplementedSpellingBeeServer
// for forward compatibility.
//
// this is our service. client can call these 2rpc methods on the server
type SpellingBeeServer interface {
	StartGame(context.Context, *StartRequest) (*StartResponse, error)
	SubmitWord(context.Context, *WordRequest) (*WordResponse, error)
	mustEmbedUnimplementedSpellingBeeServer()
}

// UnimplementedSpellingBeeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpellingBeeServer struct{}

func (UnimplementedSpellingBeeServer) StartGame(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedSpellingBeeServer) SubmitWord(context.Context, *WordRequest) (*WordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWord not implemented")
}
func (UnimplementedSpellingBeeServer) mustEmbedUnimplementedSpellingBeeServer() {}
func (UnimplementedSpellingBeeServer) testEmbeddedByValue()                     {}

// UnsafeSpellingBeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpellingBeeServer will
// result in compilation errors.
type UnsafeSpellingBeeServer interface {
	mustEmbedUnimplementedSpellingBeeServer()
}

func RegisterSpellingBeeServer(s grpc.ServiceRegistrar, srv SpellingBeeServer) {
	// If the following call pancis, it indicates UnimplementedSpellingBeeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpellingBee_ServiceDesc, srv)
}

func _SpellingBee_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpellingBeeServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpellingBee_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpellingBeeServer).StartGame(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpellingBee_SubmitWord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpellingBeeServer).SubmitWord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpellingBee_SubmitWord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpellingBeeServer).SubmitWord(ctx, req.(*WordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpellingBee_ServiceDesc is the grpc.ServiceDesc for SpellingBee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpellingBee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spellingbee.v1.SpellingBee",
	HandlerType: (*SpellingBeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartGame",
			Handler:    _SpellingBee_StartGame_Handler,
		},
		{
			MethodName: "SubmitWord",
			Handler:    _SpellingBee_SubmitWord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/spellingbee/v1/game.proto",
}
